package com.tsi2.streamrain.model.main;
// Generated 04/10/2017 11:18:37 PM by Hibernate Tools 4.3.1



/**
 * Tenants generated by hbm2java
 */
public class Tenants  implements java.io.Serializable {


    private Integer id;
    private String name;
    private String dbIp;
    private int dbPort;
    private String dbUser;
    private String dbPassword;
    private String generatorUser;
    private String generatorPassword;

   public Tenants() {
   }

   public Tenants(String name, String dbIp, int dbPort, String dbUser, String dbPassword, String generatorUser, String generatorPassword) {
      this.name = name;
      this.dbIp = dbIp;
      this.dbPort = dbPort;
      this.dbUser = dbUser;
      this.dbPassword = dbPassword;
      this.generatorUser = generatorUser;
      this.generatorPassword = generatorPassword;
   }
  
   public Integer getId() {
       return this.id;
   }
   
   public void setId(Integer id) {
       this.id = id;
   }
   public String getName() {
       return this.name;
   }
   
   public void setName(String name) {
       this.name = name;
   }
   public String getDbIp() {
       return this.dbIp;
   }
   
   public void setDbIp(String dbIp) {
       this.dbIp = dbIp;
   }
   public int getDbPort() {
       return this.dbPort;
   }
   
   public void setDbPort(int dbPort) {
       this.dbPort = dbPort;
   }
   public String getDbUser() {
       return this.dbUser;
   }
   
   public void setDbUser(String dbUser) {
       this.dbUser = dbUser;
   }
   public String getDbPassword() {
       return this.dbPassword;
   }
   
   public void setDbPassword(String dbPassword) {
       this.dbPassword = dbPassword;
   }
   public String getGeneratorUser() {
       return this.generatorUser;
   }
   
   public void setGeneratorUser(String generatorUser) {
       this.generatorUser = generatorUser;
   }
   public String getGeneratorPassword() {
       return this.generatorPassword;
   }
   
   public void setGeneratorPassword(String generatorPassword) {
       this.generatorPassword = generatorPassword;
   }

}

