package com.tsi2.streamrain.model.generator;

import java.util.HashSet;
import java.util.Set;

/**
 * AlwaysAvailableContents generated by hbm2java
 */
public class AlwaysAvailableContents  implements java.io.Serializable {


     private int contentId;
     private Contents contents;
     private int duration;
     private Set userCommentses = new HashSet(0);

    public AlwaysAvailableContents() {
    }

	
    public AlwaysAvailableContents(Contents contents, int duration) {
        this.contents = contents;
        this.duration = duration;
    }
    public AlwaysAvailableContents(Contents contents, int duration, Set userCommentses) {
       this.contents = contents;
       this.duration = duration;
       this.userCommentses = userCommentses;
    }
   
    public int getContentId() {
        return this.contentId;
    }
    
    public void setContentId(int contentId) {
        this.contentId = contentId;
    }
    public Contents getContents() {
        return this.contents;
    }
    
    public void setContents(Contents contents) {
        this.contents = contents;
    }
    public int getDuration() {
        return this.duration;
    }
    
    public void setDuration(int duration) {
        this.duration = duration;
    }
    public Set getUserCommentses() {
        return this.userCommentses;
    }
    
    public void setUserCommentses(Set userCommentses) {
        this.userCommentses = userCommentses;
    }




}


