package com.tsi2.streamrain.model.generator;


/**
 * ContentCasts generated by hbm2java
 */
public class ContentCasts  implements java.io.Serializable {


     private Integer id;
     private Contents contents;
     private String firstName;
     private String lastName;
     private String coverPhotoUrl;
     private Boolean isActor;
     private Boolean isDirector;

    public ContentCasts() {
    }

	
    public ContentCasts(Contents contents, String firstName, String lastName) {
        this.contents = contents;
        this.firstName = firstName;
        this.lastName = lastName;
    }
    public ContentCasts(Contents contents, String firstName, String lastName, String coverPhotoUrl, Boolean isActor, Boolean isDirector) {
       this.contents = contents;
       this.firstName = firstName;
       this.lastName = lastName;
       this.coverPhotoUrl = coverPhotoUrl;
       this.isActor = isActor;
       this.isDirector = isDirector;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Contents getContents() {
        return this.contents;
    }
    
    public void setContents(Contents contents) {
        this.contents = contents;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getCoverPhotoUrl() {
        return this.coverPhotoUrl;
    }
    
    public void setCoverPhotoUrl(String coverPhotoUrl) {
        this.coverPhotoUrl = coverPhotoUrl;
    }
    public Boolean getIsActor() {
        return this.isActor;
    }
    
    public void setIsActor(Boolean isActor) {
        this.isActor = isActor;
    }
    public Boolean getIsDirector() {
        return this.isDirector;
    }
    
    public void setIsDirector(Boolean isDirector) {
        this.isDirector = isDirector;
    }




}


