package com.tsi2.streamrain.model.generator;
// Generated 04/10/2017 11:03:07 PM by Hibernate Tools 4.3.1



/**
 * ContentCastsId generated by hbm2java
 */
public class ContentCastsId  implements java.io.Serializable {


     private int contentId;
     private String firstName;
     private String lastName;

    public ContentCastsId() {
    }

    public ContentCastsId(int contentId, String firstName, String lastName) {
       this.contentId = contentId;
       this.firstName = firstName;
       this.lastName = lastName;
    }
   
    public int getContentId() {
        return this.contentId;
    }
    
    public void setContentId(int contentId) {
        this.contentId = contentId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ContentCastsId) ) return false;
		 ContentCastsId castOther = ( ContentCastsId ) other; 
         
		 return (this.getContentId()==castOther.getContentId())
 && ( (this.getFirstName()==castOther.getFirstName()) || ( this.getFirstName()!=null && castOther.getFirstName()!=null && this.getFirstName().equals(castOther.getFirstName()) ) )
 && ( (this.getLastName()==castOther.getLastName()) || ( this.getLastName()!=null && castOther.getLastName()!=null && this.getLastName().equals(castOther.getLastName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getContentId();
         result = 37 * result + ( getFirstName() == null ? 0 : this.getFirstName().hashCode() );
         result = 37 * result + ( getLastName() == null ? 0 : this.getLastName().hashCode() );
         return result;
   }   


}


