package com.tsi2.streamrain.model.generator;
// Generated 04/10/2017 11:03:07 PM by Hibernate Tools 4.3.1



/**
 * ContentCasts generated by hbm2java
 */
public class ContentCasts  implements java.io.Serializable {


     private ContentCastsId id;
     private Contents contents;
     private String coverPhotoUrl;
     private Boolean isActor;
     private Boolean isDirector;

    public ContentCasts() {
    }

	
    public ContentCasts(ContentCastsId id, Contents contents) {
        this.id = id;
        this.contents = contents;
    }
    public ContentCasts(ContentCastsId id, Contents contents, String coverPhotoUrl, Boolean isActor, Boolean isDirector) {
       this.id = id;
       this.contents = contents;
       this.coverPhotoUrl = coverPhotoUrl;
       this.isActor = isActor;
       this.isDirector = isDirector;
    }
   
    public ContentCastsId getId() {
        return this.id;
    }
    
    public void setId(ContentCastsId id) {
        this.id = id;
    }
    public Contents getContents() {
        return this.contents;
    }
    
    public void setContents(Contents contents) {
        this.contents = contents;
    }
    public String getCoverPhotoUrl() {
        return this.coverPhotoUrl;
    }
    
    public void setCoverPhotoUrl(String coverPhotoUrl) {
        this.coverPhotoUrl = coverPhotoUrl;
    }
    public Boolean getIsActor() {
        return this.isActor;
    }
    
    public void setIsActor(Boolean isActor) {
        this.isActor = isActor;
    }
    public Boolean getIsDirector() {
        return this.isDirector;
    }
    
    public void setIsDirector(Boolean isDirector) {
        this.isDirector = isDirector;
    }




}


