package com.tsi2.streamrain.model.generator;
// Generated 04/10/2017 11:03:07 PM by Hibernate Tools 4.3.1



/**
 * ContentCasts generated by hbm2java
 */
public class ContentCasts  implements java.io.Serializable {


	 private Integer id;
     private Contents contents;
     private String firstName;
     private String lastName;
     private String coverPhotoUrl;
     private Boolean isActor;
     private Boolean isDirector;

    public ContentCasts() {
    }

	
    public ContentCasts(Contents contents, String firstName, String lastName, String coverPhotoUrl, Boolean isActor, Boolean isDirector) {
       this.contents = contents;
       this.firstName = firstName;
       this.lastName = lastName;
       this.coverPhotoUrl = coverPhotoUrl;
       this.isActor = isActor;
       this.isDirector = isDirector;
    }
   
    
    public Integer getId() {
		return id;
	}


	public void setId(Integer id) {
		this.id = id;
	}

	
	public String getFirstName() {
		return firstName;
	}


	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}


	public String getLastName() {
		return lastName;
	}


	public void setLastName(String lastName) {
		this.lastName = lastName;
	}


	public Contents getContents() {
        return this.contents;
    }
    
    public void setContents(Contents contents) {
        this.contents = contents;
    }
    public String getCoverPhotoUrl() {
        return this.coverPhotoUrl;
    }
    
    public void setCoverPhotoUrl(String coverPhotoUrl) {
        this.coverPhotoUrl = coverPhotoUrl;
    }
    public Boolean getIsActor() {
        return this.isActor;
    }
    
    public void setIsActor(Boolean isActor) {
        this.isActor = isActor;
    }
    public Boolean getIsDirector() {
        return this.isDirector;
    }
    
    public void setIsDirector(Boolean isDirector) {
        this.isDirector = isDirector;
    }




}


