package com.tsi2.streamrain.model.generator;
// Generated 04/10/2017 11:03:07 PM by Hibernate Tools 4.3.1



/**
 * ContentCollectionsId generated by hbm2java
 */
public class ContentCollectionsId  implements java.io.Serializable {


     private int collectionId;
     private int contentId;

    public ContentCollectionsId() {
    }

    public ContentCollectionsId(int collectionId, int contentId) {
       this.collectionId = collectionId;
       this.contentId = contentId;
    }
   
    public int getCollectionId() {
        return this.collectionId;
    }
    
    public void setCollectionId(int collectionId) {
        this.collectionId = collectionId;
    }
    public int getContentId() {
        return this.contentId;
    }
    
    public void setContentId(int contentId) {
        this.contentId = contentId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ContentCollectionsId) ) return false;
		 ContentCollectionsId castOther = ( ContentCollectionsId ) other; 
         
		 return (this.getCollectionId()==castOther.getCollectionId())
 && (this.getContentId()==castOther.getContentId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCollectionId();
         result = 37 * result + this.getContentId();
         return result;
   }   


}


