package com.tsi2.streamrain.model.generator;

/**
 * ContentCollections generated by hbm2java
 */
public class ContentCollections  implements java.io.Serializable {


     private ContentCollectionsId id;
     private Collections collections;
     private Contents contents;
     private int number;

    public ContentCollections() {
    }

    public ContentCollections(ContentCollectionsId id, Collections collections, Contents contents, int number) {
       this.id = id;
       this.collections = collections;
       this.contents = contents;
       this.number = number;
    }
   
    public ContentCollectionsId getId() {
        return this.id;
    }
    
    public void setId(ContentCollectionsId id) {
        this.id = id;
    }
    public Collections getCollections() {
        return this.collections;
    }
    
    public void setCollections(Collections collections) {
        this.collections = collections;
    }
    public Contents getContents() {
        return this.contents;
    }
    
    public void setContents(Contents contents) {
        this.contents = contents;
    }
    public int getNumber() {
        return this.number;
    }
    
    public void setNumber(int number) {
        this.number = number;
    }




}


