package com.tsi2.streamrain.model.generator;

import java.util.Date;

/**
 * JanusServers generated by hbm2java
 */
public class JanusServers  implements java.io.Serializable {


     private Integer id;
     private JanusCreationTokens janusCreationTokens;
     private String name;
     private boolean isEnable;
     private String janusUrl;
     private String adminUrl;
     private String stunServer;
     private String adminSecret;
     private String adminKey;
     private String streamrainRestToken;
     private Date dateLastUpdateRequest;

    public JanusServers() {
    }

	
    public JanusServers(JanusCreationTokens janusCreationTokens, String name, boolean isEnable, String janusUrl, String adminUrl, String stunServer, String adminSecret, String adminKey) {
        this.janusCreationTokens = janusCreationTokens;
        this.name = name;
        this.isEnable = isEnable;
        this.janusUrl = janusUrl;
        this.adminUrl = adminUrl;
        this.stunServer = stunServer;
        this.adminSecret = adminSecret;
        this.adminKey = adminKey;
    }
    public JanusServers(JanusCreationTokens janusCreationTokens, String name, boolean isEnable, String janusUrl, String adminUrl, String stunServer, String adminSecret, String adminKey, String streamrainRestToken, Date dateLastUpdateRequest) {
       this.janusCreationTokens = janusCreationTokens;
       this.name = name;
       this.isEnable = isEnable;
       this.janusUrl = janusUrl;
       this.adminUrl = adminUrl;
       this.stunServer = stunServer;
       this.adminSecret = adminSecret;
       this.adminKey = adminKey;
       this.streamrainRestToken = streamrainRestToken;
       this.dateLastUpdateRequest = dateLastUpdateRequest;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public JanusCreationTokens getJanusCreationTokens() {
        return this.janusCreationTokens;
    }
    
    public void setJanusCreationTokens(JanusCreationTokens janusCreationTokens) {
        this.janusCreationTokens = janusCreationTokens;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public boolean isIsEnable() {
        return this.isEnable;
    }
    
    public void setIsEnable(boolean isEnable) {
        this.isEnable = isEnable;
    }
    public String getJanusUrl() {
        return this.janusUrl;
    }
    
    public void setJanusUrl(String janusUrl) {
        this.janusUrl = janusUrl;
    }
    public String getAdminUrl() {
        return this.adminUrl;
    }
    
    public void setAdminUrl(String adminUrl) {
        this.adminUrl = adminUrl;
    }
    public String getStunServer() {
        return this.stunServer;
    }
    
    public void setStunServer(String stunServer) {
        this.stunServer = stunServer;
    }
    public String getAdminSecret() {
        return this.adminSecret;
    }
    
    public void setAdminSecret(String adminSecret) {
        this.adminSecret = adminSecret;
    }
    public String getAdminKey() {
        return this.adminKey;
    }
    
    public void setAdminKey(String adminKey) {
        this.adminKey = adminKey;
    }
    public String getStreamrainRestToken() {
        return this.streamrainRestToken;
    }
    
    public void setStreamrainRestToken(String streamrainRestToken) {
        this.streamrainRestToken = streamrainRestToken;
    }
    public Date getDateLastUpdateRequest() {
        return this.dateLastUpdateRequest;
    }
    
    public void setDateLastUpdateRequest(Date dateLastUpdateRequest) {
        this.dateLastUpdateRequest = dateLastUpdateRequest;
    }




}


