package com.tsi2.streamrain.model.generator;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JanusCreationTokens generated by hbm2java
 */
public class JanusCreationTokens  implements java.io.Serializable {


     private Integer id;
     private String janusToken;
     private String streamrainRestBackend;
     private Date dateCreation;
     private Date dateExpiration;
     private Date dateUsage;
     private Set janusServerses = new HashSet(0);

    public JanusCreationTokens() {
    }

	
    public JanusCreationTokens(String janusToken, String streamrainRestBackend, Date dateCreation, Date dateExpiration) {
        this.janusToken = janusToken;
        this.streamrainRestBackend = streamrainRestBackend;
        this.dateCreation = dateCreation;
        this.dateExpiration = dateExpiration;
    }
    public JanusCreationTokens(String janusToken, String streamrainRestBackend, Date dateCreation, Date dateExpiration, Date dateUsage, Set janusServerses) {
       this.janusToken = janusToken;
       this.streamrainRestBackend = streamrainRestBackend;
       this.dateCreation = dateCreation;
       this.dateExpiration = dateExpiration;
       this.dateUsage = dateUsage;
       this.janusServerses = janusServerses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getJanusToken() {
        return this.janusToken;
    }
    
    public void setJanusToken(String janusToken) {
        this.janusToken = janusToken;
    }
    public String getStreamrainRestBackend() {
        return this.streamrainRestBackend;
    }
    
    public void setStreamrainRestBackend(String streamrainRestBackend) {
        this.streamrainRestBackend = streamrainRestBackend;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }
    public Date getDateExpiration() {
        return this.dateExpiration;
    }
    
    public void setDateExpiration(Date dateExpiration) {
        this.dateExpiration = dateExpiration;
    }
    public Date getDateUsage() {
        return this.dateUsage;
    }
    
    public void setDateUsage(Date dateUsage) {
        this.dateUsage = dateUsage;
    }
    public Set getJanusServerses() {
        return this.janusServerses;
    }
    
    public void setJanusServerses(Set janusServerses) {
        this.janusServerses = janusServerses;
    }




}


