package com.tsi2.streamrain.model.generator;
// Generated 04/10/2017 11:03:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LiveOnlyContents generated by hbm2java
 */
public class LiveOnlyContents  implements java.io.Serializable {


     private int contentId;
     private Contents contents;
     private Date dateStart;
     private Integer estimatedDuraction;
     private Set userChatMessgeses = new HashSet(0);

    public LiveOnlyContents() {
    }

	
    public LiveOnlyContents(Contents contents, Date dateStart) {
        this.contents = contents;
        this.dateStart = dateStart;
    }
    public LiveOnlyContents(Contents contents, Date dateStart, Integer estimatedDuraction, Set userChatMessgeses) {
       this.contents = contents;
       this.dateStart = dateStart;
       this.estimatedDuraction = estimatedDuraction;
       this.userChatMessgeses = userChatMessgeses;
    }
   
    public int getContentId() {
        return this.contentId;
    }
    
    public void setContentId(int contentId) {
        this.contentId = contentId;
    }
    public Contents getContents() {
        return this.contents;
    }
    
    public void setContents(Contents contents) {
        this.contents = contents;
    }
    public Date getDateStart() {
        return this.dateStart;
    }
    
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }
    public Integer getEstimatedDuraction() {
        return this.estimatedDuraction;
    }
    
    public void setEstimatedDuraction(Integer estimatedDuraction) {
        this.estimatedDuraction = estimatedDuraction;
    }
    public Set getUserChatMessgeses() {
        return this.userChatMessgeses;
    }
    
    public void setUserChatMessgeses(Set userChatMessgeses) {
        this.userChatMessgeses = userChatMessgeses;
    }




}


