package com.tsi2.streamrain.model.generator;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LiveOnlyContents generated by hbm2java
 */
public class LiveOnlyContents  implements java.io.Serializable {


     private int contentId;
     private Contents contents;
     private Date dateStart;
     private Integer estimatedDuraction;
     private String janusPin;
     private boolean janusAudio;
     private Integer janusAudioPort;
     private Integer janusAudioPt;
     private String janusAudioRtpMap;
     private boolean janusVideo;
     private Integer janusVideoPort;
     private Integer janusVideoPt;
     private String janusVideoRtpMap;
     private Set userChatMessgeses = new HashSet(0);

    public LiveOnlyContents() {
    }

	
    public LiveOnlyContents(Contents contents, Date dateStart, boolean janusAudio, boolean janusVideo) {
        this.contents = contents;
        this.dateStart = dateStart;
        this.janusAudio = janusAudio;
        this.janusVideo = janusVideo;
    }
    public LiveOnlyContents(Contents contents, Date dateStart, Integer estimatedDuraction, String janusPin, boolean janusAudio, Integer janusAudioPort, Integer janusAudioPt, String janusAudioRtpMap, boolean janusVideo, Integer janusVideoPort, Integer janusVideoPt, String janusVideoRtpMap, Set userChatMessgeses) {
       this.contents = contents;
       this.dateStart = dateStart;
       this.estimatedDuraction = estimatedDuraction;
       this.janusPin = janusPin;
       this.janusAudio = janusAudio;
       this.janusAudioPort = janusAudioPort;
       this.janusAudioPt = janusAudioPt;
       this.janusAudioRtpMap = janusAudioRtpMap;
       this.janusVideo = janusVideo;
       this.janusVideoPort = janusVideoPort;
       this.janusVideoPt = janusVideoPt;
       this.janusVideoRtpMap = janusVideoRtpMap;
       this.userChatMessgeses = userChatMessgeses;
    }
   
    public int getContentId() {
        return this.contentId;
    }
    
    public void setContentId(int contentId) {
        this.contentId = contentId;
    }
    public Contents getContents() {
        return this.contents;
    }
    
    public void setContents(Contents contents) {
        this.contents = contents;
    }
    public Date getDateStart() {
        return this.dateStart;
    }
    
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }
    public Integer getEstimatedDuraction() {
        return this.estimatedDuraction;
    }
    
    public void setEstimatedDuraction(Integer estimatedDuraction) {
        this.estimatedDuraction = estimatedDuraction;
    }
    public String getJanusPin() {
        return this.janusPin;
    }
    
    public void setJanusPin(String janusPin) {
        this.janusPin = janusPin;
    }
    public boolean isJanusAudio() {
        return this.janusAudio;
    }
    
    public void setJanusAudio(boolean janusAudio) {
        this.janusAudio = janusAudio;
    }
    public Integer getJanusAudioPort() {
        return this.janusAudioPort;
    }
    
    public void setJanusAudioPort(Integer janusAudioPort) {
        this.janusAudioPort = janusAudioPort;
    }
    public Integer getJanusAudioPt() {
        return this.janusAudioPt;
    }
    
    public void setJanusAudioPt(Integer janusAudioPt) {
        this.janusAudioPt = janusAudioPt;
    }
    public String getJanusAudioRtpMap() {
        return this.janusAudioRtpMap;
    }
    
    public void setJanusAudioRtpMap(String janusAudioRtpMap) {
        this.janusAudioRtpMap = janusAudioRtpMap;
    }
    public boolean isJanusVideo() {
        return this.janusVideo;
    }
    
    public void setJanusVideo(boolean janusVideo) {
        this.janusVideo = janusVideo;
    }
    public Integer getJanusVideoPort() {
        return this.janusVideoPort;
    }
    
    public void setJanusVideoPort(Integer janusVideoPort) {
        this.janusVideoPort = janusVideoPort;
    }
    public Integer getJanusVideoPt() {
        return this.janusVideoPt;
    }
    
    public void setJanusVideoPt(Integer janusVideoPt) {
        this.janusVideoPt = janusVideoPt;
    }
    public String getJanusVideoRtpMap() {
        return this.janusVideoRtpMap;
    }
    
    public void setJanusVideoRtpMap(String janusVideoRtpMap) {
        this.janusVideoRtpMap = janusVideoRtpMap;
    }
    public Set getUserChatMessgeses() {
        return this.userChatMessgeses;
    }
    
    public void setUserChatMessgeses(Set userChatMessgeses) {
        this.userChatMessgeses = userChatMessgeses;
    }




}


