package com.tsi2.streamrain.model.generator;
// Generated 04/10/2017 11:03:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PaymentMethods generated by hbm2java
 */
public class PaymentMethods  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set userSubscriptionses = new HashSet(0);
     private Set userPpvses = new HashSet(0);

    public PaymentMethods() {
    }

	
    public PaymentMethods(String name) {
        this.name = name;
    }
    public PaymentMethods(String name, Set userSubscriptionses, Set userPpvses) {
       this.name = name;
       this.userSubscriptionses = userSubscriptionses;
       this.userPpvses = userPpvses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUserSubscriptionses() {
        return this.userSubscriptionses;
    }
    
    public void setUserSubscriptionses(Set userSubscriptionses) {
        this.userSubscriptionses = userSubscriptionses;
    }
    public Set getUserPpvses() {
        return this.userPpvses;
    }
    
    public void setUserPpvses(Set userPpvses) {
        this.userPpvses = userPpvses;
    }




}


