package com.tsi2.streamrain.model.generator;
// Generated 04/10/2017 11:03:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SharedContents generated by hbm2java
 */
public class SharedContents  implements java.io.Serializable {


     private Integer id;
     private Contents contents;
     private Users usersByDestinationUserId;
     private Users usersByUserId;
     private Date date;

    public SharedContents() {
    }

    public SharedContents(Contents contents, Users usersByDestinationUserId, Users usersByUserId, Date date) {
       this.contents = contents;
       this.usersByDestinationUserId = usersByDestinationUserId;
       this.usersByUserId = usersByUserId;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Contents getContents() {
        return this.contents;
    }
    
    public void setContents(Contents contents) {
        this.contents = contents;
    }
    public Users getUsersByDestinationUserId() {
        return this.usersByDestinationUserId;
    }
    
    public void setUsersByDestinationUserId(Users usersByDestinationUserId) {
        this.usersByDestinationUserId = usersByDestinationUserId;
    }
    public Users getUsersByUserId() {
        return this.usersByUserId;
    }
    
    public void setUsersByUserId(Users usersByUserId) {
        this.usersByUserId = usersByUserId;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


