package com.tsi2.streamrain.model.generator;

/**
 * SpoilerMarksId generated by hbm2java
 */
public class SpoilerMarksId  implements java.io.Serializable {


     private int userId;
     private int userCommentId;

    public SpoilerMarksId() {
    }

    public SpoilerMarksId(int userId, int userCommentId) {
       this.userId = userId;
       this.userCommentId = userCommentId;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getUserCommentId() {
        return this.userCommentId;
    }
    
    public void setUserCommentId(int userCommentId) {
        this.userCommentId = userCommentId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SpoilerMarksId) ) return false;
		 SpoilerMarksId castOther = ( SpoilerMarksId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getUserCommentId()==castOther.getUserCommentId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getUserCommentId();
         return result;
   }   


}


