package com.tsi2.streamrain.model.generator;
// Generated 04/10/2017 11:03:07 PM by Hibernate Tools 4.3.1



/**
 * UserPpvsId generated by hbm2java
 */
public class UserPpvsId  implements java.io.Serializable {


     private int userId;
     private int contentId;

    public UserPpvsId() {
    }

    public UserPpvsId(int userId, int contentId) {
       this.userId = userId;
       this.contentId = contentId;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getContentId() {
        return this.contentId;
    }
    
    public void setContentId(int contentId) {
        this.contentId = contentId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserPpvsId) ) return false;
		 UserPpvsId castOther = ( UserPpvsId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getContentId()==castOther.getContentId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getContentId();
         return result;
   }   


}


