package com.tsi2.streamrain.model.generator;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserChatMessges generated by hbm2java
 */
public class UserChatMessges  implements java.io.Serializable {


     private Integer id;
     private LiveOnlyContents liveOnlyContents;
     private Users users;
     private Date date;
     private String text;
     private Boolean isDeleted;
     private Set userses = new HashSet(0);

    public UserChatMessges() {
    }

	
    public UserChatMessges(LiveOnlyContents liveOnlyContents, Users users, Date date, String text) {
        this.liveOnlyContents = liveOnlyContents;
        this.users = users;
        this.date = date;
        this.text = text;
    }
    public UserChatMessges(LiveOnlyContents liveOnlyContents, Users users, Date date, String text, Boolean isDeleted, Set userses) {
       this.liveOnlyContents = liveOnlyContents;
       this.users = users;
       this.date = date;
       this.text = text;
       this.isDeleted = isDeleted;
       this.userses = userses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public LiveOnlyContents getLiveOnlyContents() {
        return this.liveOnlyContents;
    }
    
    public void setLiveOnlyContents(LiveOnlyContents liveOnlyContents) {
        this.liveOnlyContents = liveOnlyContents;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


