package com.tsi2.streamrain.model.generator;
// Generated 04/10/2017 11:03:07 PM by Hibernate Tools 4.3.1



/**
 * UserRatings generated by hbm2java
 */
public class UserRatings  implements java.io.Serializable {


     private UserRatingsId id;
     private Contents contents;
     private Users users;
     private int rate;
     private Boolean useForRecommendations;

    public UserRatings() {
    }

	
    public UserRatings(UserRatingsId id, Contents contents, Users users, int rate) {
        this.id = id;
        this.contents = contents;
        this.users = users;
        this.rate = rate;
    }
    public UserRatings(UserRatingsId id, Contents contents, Users users, int rate, Boolean useForRecommendations) {
       this.id = id;
       this.contents = contents;
       this.users = users;
       this.rate = rate;
       this.useForRecommendations = useForRecommendations;
    }
   
    public UserRatingsId getId() {
        return this.id;
    }
    
    public void setId(UserRatingsId id) {
        this.id = id;
    }
    public Contents getContents() {
        return this.contents;
    }
    
    public void setContents(Contents contents) {
        this.contents = contents;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public int getRate() {
        return this.rate;
    }
    
    public void setRate(int rate) {
        this.rate = rate;
    }
    public Boolean getUseForRecommendations() {
        return this.useForRecommendations;
    }
    
    public void setUseForRecommendations(Boolean useForRecommendations) {
        this.useForRecommendations = useForRecommendations;
    }




}


