package com.tsi2.streamrain.model.generator;
// Generated 04/10/2017 11:03:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserSubscriptions generated by hbm2java
 */
public class UserSubscriptions  implements java.io.Serializable {


     private Integer id;
     private PaymentMethods paymentMethods;
     private Users users;
     private Date datePayment;
     private Date dateStart;
     private Date dateFinish;

    public UserSubscriptions() {
    }

    public UserSubscriptions(PaymentMethods paymentMethods, Users users, Date datePayment, Date dateStart, Date dateFinish) {
       this.paymentMethods = paymentMethods;
       this.users = users;
       this.datePayment = datePayment;
       this.dateStart = dateStart;
       this.dateFinish = dateFinish;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public PaymentMethods getPaymentMethods() {
        return this.paymentMethods;
    }
    
    public void setPaymentMethods(PaymentMethods paymentMethods) {
        this.paymentMethods = paymentMethods;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getDatePayment() {
        return this.datePayment;
    }
    
    public void setDatePayment(Date datePayment) {
        this.datePayment = datePayment;
    }
    public Date getDateStart() {
        return this.dateStart;
    }
    
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }
    public Date getDateFinish() {
        return this.dateFinish;
    }
    
    public void setDateFinish(Date dateFinish) {
        this.dateFinish = dateFinish;
    }




}


