package com.tsi2.streamrain.model.generator;

import java.util.Date;

/**
 * UserPpvs generated by hbm2java
 */
public class UserPpvs  implements java.io.Serializable {


     private UserPpvsId id;
     private Contents contents;
     private PaymentMethods paymentMethods;
     private Users users;
     private Date datePayment;

    public UserPpvs() {
    }

    public UserPpvs(UserPpvsId id, Contents contents, PaymentMethods paymentMethods, Users users, Date datePayment) {
       this.id = id;
       this.contents = contents;
       this.paymentMethods = paymentMethods;
       this.users = users;
       this.datePayment = datePayment;
    }
   
    public UserPpvsId getId() {
        return this.id;
    }
    
    public void setId(UserPpvsId id) {
        this.id = id;
    }
    public Contents getContents() {
        return this.contents;
    }
    
    public void setContents(Contents contents) {
        this.contents = contents;
    }
    public PaymentMethods getPaymentMethods() {
        return this.paymentMethods;
    }
    
    public void setPaymentMethods(PaymentMethods paymentMethods) {
        this.paymentMethods = paymentMethods;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getDatePayment() {
        return this.datePayment;
    }
    
    public void setDatePayment(Date datePayment) {
        this.datePayment = datePayment;
    }




}


