package com.tsi2.streamrain.model.generator;

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String nickname;
     private String password;
     private Boolean isBanned;
     private String country;
     private String city;
     private String facebookUserId;
     private String twitterUserId;
     private Integer integratorId;
     private Boolean blocked;
     private Set userChatMessgeses = new HashSet(0);
     private Set userCommentses = new HashSet(0);
     private Set spoilerMarkses = new HashSet(0);
     private Set userFavses = new HashSet(0);
     private Set userViewses = new HashSet(0);
     private Set sharedCollectionsesForDestinationUserId = new HashSet(0);
     private Set userChatMessgeses_1 = new HashSet(0);
     private Set sharedCollectionsesForUserId = new HashSet(0);
     private Set sharedContentsesForDestinationUserId = new HashSet(0);
     private Set sharedContentsesForUserId = new HashSet(0);
     private Set userRatingses = new HashSet(0);
     private Set userPpvses = new HashSet(0);
     private Set userSubscriptionses = new HashSet(0);

    public Users() {
    }

	
    public Users(String email, String nickname, String password, String country, String city, boolean blocked) {
        this.email = email;
        this.nickname = nickname;
        this.password = password;
        this.country = country;
        this.city = city;
        this.blocked = blocked;
    }
    public Users(String email, String nickname, String password, Boolean isBanned, String country, String city, String facebookUserId, String twitterUserId, Integer integratorId, boolean blocked, Set userChatMessgeses, Set userCommentses, Set spoilerMarkses, Set userFavses, Set userViewses, Set sharedCollectionsesForDestinationUserId, Set userChatMessgeses_1, Set sharedCollectionsesForUserId, Set sharedContentsesForDestinationUserId, Set sharedContentsesForUserId, Set userRatingses, Set userPpvses, Set userSubscriptionses) {
       this.email = email;
       this.nickname = nickname;
       this.password = password;
       this.isBanned = isBanned;
       this.country = country;
       this.city = city;
       this.facebookUserId = facebookUserId;
       this.twitterUserId = twitterUserId;
       this.integratorId = integratorId;
       this.blocked = blocked;
       this.userChatMessgeses = userChatMessgeses;
       this.userCommentses = userCommentses;
       this.spoilerMarkses = spoilerMarkses;
       this.userFavses = userFavses;
       this.userViewses = userViewses;
       this.sharedCollectionsesForDestinationUserId = sharedCollectionsesForDestinationUserId;
       this.userChatMessgeses_1 = userChatMessgeses_1;
       this.sharedCollectionsesForUserId = sharedCollectionsesForUserId;
       this.sharedContentsesForDestinationUserId = sharedContentsesForDestinationUserId;
       this.sharedContentsesForUserId = sharedContentsesForUserId;
       this.userRatingses = userRatingses;
       this.userPpvses = userPpvses;
       this.userSubscriptionses = userSubscriptionses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getIsBanned() {
        return this.isBanned;
    }
    
    public void setIsBanned(Boolean isBanned) {
        this.isBanned = isBanned;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getFacebookUserId() {
        return this.facebookUserId;
    }
    
    public void setFacebookUserId(String facebookUserId) {
        this.facebookUserId = facebookUserId;
    }
    public String getTwitterUserId() {
        return this.twitterUserId;
    }
    
    public void setTwitterUserId(String twitterUserId) {
        this.twitterUserId = twitterUserId;
    }
    public Integer getIntegratorId() {
        return this.integratorId;
    }
    
    public void setIntegratorId(Integer integratorId) {
        this.integratorId = integratorId;
    }
    public Boolean isBlocked() {
        return this.blocked;
    }
    
    public void setBlocked(Boolean blocked) {
        this.blocked = blocked;
    }
    public Set getUserChatMessgeses() {
        return this.userChatMessgeses;
    }
    
    public void setUserChatMessgeses(Set userChatMessgeses) {
        this.userChatMessgeses = userChatMessgeses;
    }
    public Set getUserCommentses() {
        return this.userCommentses;
    }
    
    public void setUserCommentses(Set userCommentses) {
        this.userCommentses = userCommentses;
    }
    public Set getSpoilerMarkses() {
        return this.spoilerMarkses;
    }
    
    public void setSpoilerMarkses(Set spoilerMarkses) {
        this.spoilerMarkses = spoilerMarkses;
    }
    public Set getUserFavses() {
        return this.userFavses;
    }
    
    public void setUserFavses(Set userFavses) {
        this.userFavses = userFavses;
    }
    public Set getUserViewses() {
        return this.userViewses;
    }
    
    public void setUserViewses(Set userViewses) {
        this.userViewses = userViewses;
    }
    public Set getSharedCollectionsesForDestinationUserId() {
        return this.sharedCollectionsesForDestinationUserId;
    }
    
    public void setSharedCollectionsesForDestinationUserId(Set sharedCollectionsesForDestinationUserId) {
        this.sharedCollectionsesForDestinationUserId = sharedCollectionsesForDestinationUserId;
    }
    public Set getUserChatMessgeses_1() {
        return this.userChatMessgeses_1;
    }
    
    public void setUserChatMessgeses_1(Set userChatMessgeses_1) {
        this.userChatMessgeses_1 = userChatMessgeses_1;
    }
    public Set getSharedCollectionsesForUserId() {
        return this.sharedCollectionsesForUserId;
    }
    
    public void setSharedCollectionsesForUserId(Set sharedCollectionsesForUserId) {
        this.sharedCollectionsesForUserId = sharedCollectionsesForUserId;
    }
    public Set getSharedContentsesForDestinationUserId() {
        return this.sharedContentsesForDestinationUserId;
    }
    
    public void setSharedContentsesForDestinationUserId(Set sharedContentsesForDestinationUserId) {
        this.sharedContentsesForDestinationUserId = sharedContentsesForDestinationUserId;
    }
    public Set getSharedContentsesForUserId() {
        return this.sharedContentsesForUserId;
    }
    
    public void setSharedContentsesForUserId(Set sharedContentsesForUserId) {
        this.sharedContentsesForUserId = sharedContentsesForUserId;
    }
    public Set getUserRatingses() {
        return this.userRatingses;
    }
    
    public void setUserRatingses(Set userRatingses) {
        this.userRatingses = userRatingses;
    }
    public Set getUserPpvses() {
        return this.userPpvses;
    }
    
    public void setUserPpvses(Set userPpvses) {
        this.userPpvses = userPpvses;
    }
    public Set getUserSubscriptionses() {
        return this.userSubscriptionses;
    }
    
    public void setUserSubscriptionses(Set userSubscriptionses) {
        this.userSubscriptionses = userSubscriptionses;
    }




}


