package com.tsi2.streamrain.model.generator;

import java.util.Date;

/**
 * UserSubscriptions generated by hbm2java
 */
public class UserSubscriptions  implements java.io.Serializable {


     private Integer id;
     private PaymentMethods paymentMethods;
     private Users users;
     private Date datePayment;
     private Date dateStart;
     private Date dateFinish;
     private String janusUserToken;

    public UserSubscriptions() {
    }

    public UserSubscriptions(PaymentMethods paymentMethods, Users users, Date datePayment, Date dateStart, Date dateFinish, String janusUserToken) {
       this.paymentMethods = paymentMethods;
       this.users = users;
       this.datePayment = datePayment;
       this.dateStart = dateStart;
       this.dateFinish = dateFinish;
       this.janusUserToken = janusUserToken;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public PaymentMethods getPaymentMethods() {
        return this.paymentMethods;
    }
    
    public void setPaymentMethods(PaymentMethods paymentMethods) {
        this.paymentMethods = paymentMethods;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getDatePayment() {
        return this.datePayment;
    }
    
    public void setDatePayment(Date datePayment) {
        this.datePayment = datePayment;
    }
    public Date getDateStart() {
        return this.dateStart;
    }
    
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }
    public Date getDateFinish() {
        return this.dateFinish;
    }
    
    public void setDateFinish(Date dateFinish) {
        this.dateFinish = dateFinish;
    }
    public String getJanusUserToken() {
        return this.janusUserToken;
    }
    
    public void setJanusUserToken(String janusUserToken) {
        this.janusUserToken = janusUserToken;
    }




}


